# Generated by Django 5.0.6 on 2024-06-21 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestao_barbearia', '0001_initial'),
        ('portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='funcao',
            name='barbearia',
            field=models.ManyToManyField(related_name='barbearia', to='portal.barbearia'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='barbearia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.barbearia'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='funcao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_barbearia.funcao'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='gestao_barbearia.funcionario'),
        ),
        migrations.AddField(
            model_name='servico',
            name='barbearia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.barbearia'),
        ),
        migrations.AddField(
            model_name='servico',
            name='funcao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_barbearia.funcao'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_barbearia.servico'),
        ),
        migrations.AlterUniqueTogether(
            name='agendamento',
            unique_together={('funcionario', 'data_hora')},
        ),
    ]
