# Generated by Django 5.0.6 on 2024-06-21 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_barbearia', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcao',
            name='barbearia',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='funcao',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='barbearia',
        ),
        migrations.AddField(
            model_name='funcao',
            name='funcionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestao_barbearia.funcionario'),
            preserve_default=False,
        ),
    ]
